my:
  greeting: Hello World from config server
  list:
    values: One,Two,Three, Four

dbValues: "{connectionString:  'http: //___', userName:  'foo', password:  'pass'}"

db:
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1200
